package team068b.behaviors;

public enum RefineryBuildOrder 
{
	WAIT_FOR_RALLY,
	EQUIPPING,
	GIVE_ANTENNA,
	DETERMINE_LEADER,
	WAIT_FOR_DOCK,
	EQUIP_FLYERS,
	WAIT_FOR_HANBANG,
	MAKE_MARINE,
	EQUIP_MARINE,
	SLEEP
}
