package team068b.behaviors;

public enum SCVBuildOrder 
{
	FIND_MINE,
	GET_OFF_MINE,
	WAIT_FOR_ANTENNA,
	BUILD_REFINERY,
	BUILD_ARMORY,
	VACATE_HOME,
	VACATE_FACTORY,
	WAIT_FOR_FACTORY,
	BUILD_FACTORY,
	SCOUT_WEST,
	SCOUT_NORTH,
	SCOUT_EAST,
	SCOUT_SOUTH,
	RETURN_HOME,
	BROADCAST_SPAWN,
	WAIT_FOR_HANBANG,
	VACATE_SPAWN,
	SLEEP,
	WEIRD_SPAWN
}
