package plasmabot2.behaviors;

public enum SCVBuildOrder 
{
	FIND_MINE,
	GET_OFF_MINE,
	WAIT_FOR_ANTENNA,
	BUILD_REFINERY,
	BUILD_ARMORY,
	VACATE_HOME,
	VACATE_FACTORY,
	WAIT_FOR_FACTORY,
	BUILD_FACTORY,
	WAIT_FOR_HANBANG,
	SLEEP,
	WEIRD_SPAWN
}
